---
version: 3

dotenv: [".env"]

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -a

  kind:bootstrap:
    desc: Bootstrap a kind cluster
    cmds:
      - task: kind:create
      - task: apply:cilium
      - task: apply:regcred
      - task: bootstrap

  gke:bootstrap:
    desc: Bootstrap a GKE cluster
    cmds:
      - task: gke:create
      - task: apply:regcred
      - task: bootstrap

  kind:create:
    desc: Create a Kind cluster
    cmds:
      - kind delete cluster --name toledo-local
      - kind create cluster --config kind-cluster-config.yaml --name toledo-local
      - kubectl cluster-info --context kind-toledo-local
    dir: ./infra/kind

  gke:create:
    desc: Create a GKE cluster (Autopilot)
    cmds:
      - pulumi login file://./
      - gcloud components install gke-gcloud-auth-plugin
      - pulumi up -y
    dir: ./infra/gke

  bootstrap:
    desc: Bootstrap Flux for GitHub
    deps: [apply:flux]
    cmds:
      - |
        export GITHUB_TOKEN=$GH_TOKEN && \
        flux bootstrap --force github \
          --owner=$GH_USER \
          --repository=$GH_REPO \
          --branch=main \
          --path=./k8s/clusters/$PLATFORM \
          --token=$GH_TOKEN \
          --personal

  apply:cilium:
    desc: Install Cilium
    cmds:
      - helm repo add cilium https://helm.cilium.io/ --force-update
      - helm install cilium cilium/cilium --version 1.15.3 --namespace kube-system

  apply:flux:
    desc: Install Flux
    cmds:
      - kubectl apply -f https://github.com/fluxcd/flux2/releases/latest/download/install.yaml

  apply:regcred:
    desc: Create a regcred secret
    cmds:
      - kubectl create secret docker-registry regcred --docker-server=ghcr.io/$GH_USER --docker-username=$GH_USER --docker-password=$GH_TOKEN
