---
version: 3

dotenv: [".env"]

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -a

  bootstrap:
    desc: Bootstrap a kind cluster
    cmds:
      - task: delete-cluster
      - task: create-cluster
      - task: bootstrap-flux

  hola-toledo:publish:
    dir: ./apps/hola-toledo
    cmds:
      - task build-and-publish

  hola-toledo:run:
    dir: ./apps/hola-toledo
    cmds:
      - task run

  create-cluster:
    desc: Create a kind cluster
    cmds:
      - kind create cluster --config kind-cluster-config.yaml --name toledo-local
      - kubectl cluster-info --context kind-toledo-local

  bootstrap-flux:
    desc: Bootstrap Flux for GitHub
    deps:
      [
        install:cilium,
        install:ingress-nginx,
        install:flux,
        install:kyverno,
        install:sealed-secret
      ]
    cmds:
      - task: configure-sealed-secrets
      - task: create-regcred
      - |
        export GITHUB_TOKEN=$GH_TOKEN && \
        flux bootstrap --force github \
          --owner=$GH_USER \
          --repository=toledo \
          --branch=main \
          --path=./k8s/clusters/kind \
          --token=$GH_TOKEN \
          --personal

  install:cilium:
    desc: Install Cilium
    cmds:
      - helm repo add cilium https://helm.cilium.io/ --force-update
      - helm install cilium cilium/cilium --version 1.15.3 --namespace kube-system

  install:ingress-nginx:
    desc: Install Ingress-Nginx
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

  install:flux:
    desc: Install Flux
    cmds:
      - kubectl apply -f https://github.com/fluxcd/flux2/releases/latest/download/install.yaml

  install:kyverno:
    desc: Install Kyverno
    cmds:
      - kubectl apply -f https://github.com/kyverno/kyverno/releases/download/v1.10.0/install.yaml --server-side=true
      - kubectl apply -f ./k8s/infrastructure/configs/regcred.clusterpolicy.kyverno.yaml

  install:sealed-secret:
    desc: Install Kyverno
    cmds:
      - helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
      - helm install sealed-secrets sealed-secrets/sealed-secrets --create-namespace --namespace sealed-secrets

  delete-cluster:
    desc: Delete a kind cluster
    cmds:
      - kind delete cluster --name toledo-local

  create-regcred:
    desc: Create a regcred secret
    cmds:
      - kubectl create secret docker-registry regcred --docker-server=$GH_REPO --docker-username=$GH_USER --docker-password=$GH_TOKEN --docker-email=$GH_EMAIL

  configure-sealed-secrets:
    desc: Configure Sealed Secrets
    cmds:
      - openssl req -x509 -days 365 -nodes -newkey rsa:4096 -keyout "{{.PRIVATEKEY}}" -out "{{.PUBLICKEY}}" -subj "/CN=sealed-secret/O=sealed-secret"
      - kubectl -n "{{.NAMESPACE}}" create secret tls "{{.SECRETNAME}}" --cert="{{.PUBLICKEY}}" --key="{{.PRIVATEKEY}}"
      - kubectl -n "{{.NAMESPACE}}" label secret "{{.SECRETNAME}}" sealedsecrets.bitnami.com/sealed-secrets-key=active
      - kubectl -n "{{.NAMESPACE}}" delete pod -l app.kubernetes.io/name=sealed-secrets
    vars:
      PRIVATEKEY: secrets/mytls.key
      PUBLICKEY: secrets/mytls.crt
      NAMESPACE: sealed-secrets
      SECRETNAME: mycustomkeys
