---
version: 3

# Load environment variables from the .env file
dotenv: [".env"]

tasks:
  # Default task to list all available tasks
  default:
    desc: List all tasks
    cmds:
      - task -a

  # Bootstrap a Kind cluster
  kind:bootstrap:
    desc: Bootstrap a Kind cluster with required components
    cmds:
      - task: kind:create
      - task: apply:regcred
      - task: flux_bootstrap

  # Create a Kind cluster
  kind:create:
    desc: Create a Kind cluster
    cmds:
      - kind delete cluster --name toledo-local
      - kind create cluster --config kind-cluster-config.yaml --name toledo-local
      - kubectl cluster-info --context kind-toledo-local
    dir: ./infra/kind

  # Bootstrap Flux for GitHub integration
  flux_bootstrap:
    desc: Bootstrap Flux for GitHub
    cmds:
      - |
        flux install
        export GITHUB_TOKEN=$GH_TOKEN && \
        flux bootstrap github \
          --owner=$GH_USER \
          --repository=$GH_REPO \
          --branch=main \
          --path=./k8s/clusters/$PLATFORM \
          --token=$GH_TOKEN \
          --personal

  # Create a Docker registry credential
  apply:regcred:
    desc: Create a Docker registry credential secret
    cmds:
      - kubectl create secret docker-registry regcred --docker-server=ghcr.io/$GH_USER --docker-username=$GH_USER --docker-password=$GH_TOKEN --dry-run=client -oyaml | kubectl apply -f -
