---
version: 3

dotenv: [".env"]

vars:
  APP: hola-toledo

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -a

  build-and-publish:
    desc: Publish a container image
    cmds:
      - dagger call publish --username={{.GH_USER}} --password=env:GH_TOKEN --source=./src

  run:
    desc: Build and run the application image
    cmds:
      - dagger call run --app-name=hola-toledo --build-src=./src as-service up
